// Auto-generálva: scripts/scrape_cases.py. A meglévő (kézzel finomított) alt-szövegek
// és leírások újrafuttatáskor megőrződnek; a kép-src/méret frissül.
export type CaseImage = { src: string; alt: string; width: number; height: number; label?: "előtte" | "utána" };
export type CaseStudy = { slug: string; title: string; description: string; images: CaseImage[] };

export const CASES: CaseStudy[] = [
  {
    "slug": "esztetikus-e-max-preskeramia-koronak",
    "title": "Esztétikus e.max préskerámia koronák",
    "description": "",
    "images": [
      {"src": "/esetek/esztetikus-e-max-preskeramia-koronak-01.jpg", "alt": "Esztétikus e.max préskerámia koronák – 1. kép", "width": 1024, "height": 667},
      {"src": "/esetek/esztetikus-e-max-preskeramia-koronak-02.jpg", "alt": "Esztétikus e.max préskerámia koronák – 2. kép", "width": 1024, "height": 668},
      {"src": "/esetek/esztetikus-e-max-preskeramia-koronak-03.jpg", "alt": "Esztétikus e.max préskerámia koronák – 3. kép", "width": 1024, "height": 668},
      {"src": "/esetek/esztetikus-e-max-preskeramia-koronak-04.jpg", "alt": "Esztétikus e.max préskerámia koronák – 4. kép", "width": 1024, "height": 668},
    ],
  },
  {
    "slug": "keramia-korona-felepitett-fogra",
    "title": "Kerámia korona felépített fogra",
    "description": "…és ami közte történt:",
    "images": [
      {"src": "/esetek/keramia-korona-felepitett-fogra-01.jpg", "alt": "Kerámia korona felépített fogra – 1. kép (előtte)", "width": 3888, "height": 2592, "label": "előtte"},
      {"src": "/esetek/keramia-korona-felepitett-fogra-02.jpg", "alt": "Kerámia korona felépített fogra – 2. kép (utána)", "width": 3888, "height": 2592, "label": "utána"},
      {"src": "/esetek/keramia-korona-felepitett-fogra-03.jpg", "alt": "Kerámia korona felépített fogra – 3. kép", "width": 3888, "height": 2592},
      {"src": "/esetek/keramia-korona-felepitett-fogra-04.jpg", "alt": "Kerámia korona felépített fogra – 4. kép", "width": 3888, "height": 2592},
      {"src": "/esetek/keramia-korona-felepitett-fogra-05.jpg", "alt": "Kerámia korona felépített fogra – 5. kép", "width": 2304, "height": 1728},
      {"src": "/esetek/keramia-korona-felepitett-fogra-06.jpg", "alt": "Kerámia korona felépített fogra – 6. kép", "width": 2304, "height": 1728},
    ],
  },
  {
    "slug": "egyszeres-inyrecesszio-sebeszeti-megoldasa",
    "title": "Egyszeres ínyrecesszió sebészeti megoldása",
    "description": "",
    "images": [
      {"src": "/esetek/egyszeres-inyrecesszio-sebeszeti-megoldasa-01.jpg", "alt": "Egyszeres ínyrecesszió sebészeti megoldása – 1. kép", "width": 2592, "height": 3888},
      {"src": "/esetek/egyszeres-inyrecesszio-sebeszeti-megoldasa-02.jpg", "alt": "Egyszeres ínyrecesszió sebészeti megoldása – 2. kép", "width": 2592, "height": 3888},
      {"src": "/esetek/egyszeres-inyrecesszio-sebeszeti-megoldasa-03.jpg", "alt": "Egyszeres ínyrecesszió sebészeti megoldása – 3. kép", "width": 2592, "height": 3888},
    ],
  },
  {
    "slug": "esztetikai-zonaban-azonnali-implantacio-elotte-utana",
    "title": "Esztétikai zónában azonnali implantáció előtte – utána",
    "description": "…és ami közte történt a pácienssel:",
    "images": [
      {"src": "/esetek/esztetikai-zonaban-azonnali-implantacio-elotte-utana-01.jpg", "alt": "Esztétikai zónában azonnali implantáció előtte – utána – 1. kép (előtte)", "width": 3888, "height": 2436, "label": "előtte"},
      {"src": "/esetek/esztetikai-zonaban-azonnali-implantacio-elotte-utana-02.jpg", "alt": "Esztétikai zónában azonnali implantáció előtte – utána – 2. kép (utána)", "width": 3888, "height": 2592, "label": "utána"},
      {"src": "/esetek/esztetikai-zonaban-azonnali-implantacio-elotte-utana-03.jpg", "alt": "Esztétikai zónában azonnali implantáció előtte – utána – 3. kép", "width": 3888, "height": 2592},
      {"src": "/esetek/esztetikai-zonaban-azonnali-implantacio-elotte-utana-04.jpg", "alt": "Esztétikai zónában azonnali implantáció előtte – utána – 4. kép", "width": 3888, "height": 2592},
      {"src": "/esetek/esztetikai-zonaban-azonnali-implantacio-elotte-utana-05.jpg", "alt": "Esztétikai zónában azonnali implantáció előtte – utána – 5. kép", "width": 3888, "height": 2592},
      {"src": "/esetek/esztetikai-zonaban-azonnali-implantacio-elotte-utana-06.jpg", "alt": "Esztétikai zónában azonnali implantáció előtte – utána – 6. kép", "width": 3888, "height": 2592},
      {"src": "/esetek/esztetikai-zonaban-azonnali-implantacio-elotte-utana-07.jpg", "alt": "Esztétikai zónában azonnali implantáció előtte – utána – 7. kép", "width": 3888, "height": 2592},
      {"src": "/esetek/esztetikai-zonaban-azonnali-implantacio-elotte-utana-08.jpg", "alt": "Esztétikai zónában azonnali implantáció előtte – utána – 8. kép", "width": 3888, "height": 2592},
      {"src": "/esetek/esztetikai-zonaban-azonnali-implantacio-elotte-utana-09.jpg", "alt": "Esztétikai zónában azonnali implantáció előtte – utána – 9. kép", "width": 3888, "height": 2592},
      {"src": "/esetek/esztetikai-zonaban-azonnali-implantacio-elotte-utana-10.jpg", "alt": "Esztétikai zónában azonnali implantáció előtte – utána – 10. kép", "width": 3888, "height": 2592},
    ],
  },
  {
    "slug": "molaris-fog-potlasa-implantatummal",
    "title": "Moláris fog pótlása implantátummal",
    "description": "…és ami közte történt:",
    "images": [
      {"src": "/esetek/molaris-fog-potlasa-implantatummal-01.jpg", "alt": "Moláris fog pótlása implantátummal – 1. kép (előtte)", "width": 640, "height": 480, "label": "előtte"},
      {"src": "/esetek/molaris-fog-potlasa-implantatummal-02.jpg", "alt": "Moláris fog pótlása implantátummal – 2. kép (utána)", "width": 3888, "height": 2592, "label": "utána"},
      {"src": "/esetek/molaris-fog-potlasa-implantatummal-03.jpg", "alt": "Moláris fog pótlása implantátummal – 3. kép", "width": 640, "height": 480},
      {"src": "/esetek/molaris-fog-potlasa-implantatummal-04.jpg", "alt": "Moláris fog pótlása implantátummal – 4. kép", "width": 2048, "height": 1536},
      {"src": "/esetek/molaris-fog-potlasa-implantatummal-05.jpg", "alt": "Moláris fog pótlása implantátummal – 5. kép", "width": 2048, "height": 1536},
      {"src": "/esetek/molaris-fog-potlasa-implantatummal-06.jpg", "alt": "Moláris fog pótlása implantátummal – 6. kép", "width": 640, "height": 480},
      {"src": "/esetek/molaris-fog-potlasa-implantatummal-07.jpg", "alt": "Moláris fog pótlása implantátummal – 7. kép", "width": 640, "height": 480},
      {"src": "/esetek/molaris-fog-potlasa-implantatummal-08.jpg", "alt": "Moláris fog pótlása implantátummal – 8. kép", "width": 3888, "height": 2592},
      {"src": "/esetek/molaris-fog-potlasa-implantatummal-09.jpg", "alt": "Moláris fog pótlása implantátummal – 9. kép", "width": 3888, "height": 2592},
      {"src": "/esetek/molaris-fog-potlasa-implantatummal-10.jpg", "alt": "Moláris fog pótlása implantátummal – 10. kép", "width": 3888, "height": 2592},
      {"src": "/esetek/molaris-fog-potlasa-implantatummal-11.jpg", "alt": "Moláris fog pótlása implantátummal – 11. kép", "width": 3888, "height": 2592},
      {"src": "/esetek/molaris-fog-potlasa-implantatummal-12.jpg", "alt": "Moláris fog pótlása implantátummal – 12. kép", "width": 2592, "height": 3888},
      {"src": "/esetek/molaris-fog-potlasa-implantatummal-13.jpg", "alt": "Moláris fog pótlása implantátummal – 13. kép", "width": 3888, "height": 2592},
      {"src": "/esetek/molaris-fog-potlasa-implantatummal-14.jpg", "alt": "Moláris fog pótlása implantátummal – 14. kép", "width": 3888, "height": 2592},
      {"src": "/esetek/molaris-fog-potlasa-implantatummal-15.jpg", "alt": "Moláris fog pótlása implantátummal – 15. kép", "width": 3888, "height": 2592},
      {"src": "/esetek/molaris-fog-potlasa-implantatummal-16.jpg", "alt": "Moláris fog pótlása implantátummal – 16. kép", "width": 3888, "height": 2592},
      {"src": "/esetek/molaris-fog-potlasa-implantatummal-17.jpg", "alt": "Moláris fog pótlása implantátummal – 17. kép", "width": 3888, "height": 2592},
    ],
  },
  {
    "slug": "tobbszoros-inyrecesszio-kezelese-tunnel-technikaval-es-palat",
    "title": "Többszörös ínyrecesszió kezelése tunnel technikával és palatinális kötőszövetes szabadlebennyel",
    "description": "Gyakoriak azok az esetek, amikor az ínylehúzódás több fogat is érint. Kiemelten fontos megoldani ezeket a helyzeteket az esztétikai zónában, amikor a frontfogak vannak veszélyben, vagy nagyon érzékenyek. A következő páciens esetében is az előkészítést követően szintén parodontális mikrosebészeti plasztikai beavatkozást végeztünk, csak a fogközök megnyitása nélküli, úgynevezett “tunnel” technikával. A preparált “alagútba” húztuk bele a szájpadlásból kivett kötőszövetes szabadlebenyt, majd speciális varratokat alkalmazva függesztettük fel és pozícionáltuk az ínyt. Az itt bemutatott eset értéke abban jelentős, hogy be tudjuk mutatni a műtétet követő 1 éves, majd a 7 éves eredményeinket is. A recesszió fedésének sikeressége 7 év után is közel 100%-os. Ezek az eredmények bármely külföldi szakmai fórumon megállják helyüket.",
    "images": [
      {"src": "/esetek/tobbszoros-inyrecesszio-kezelese-tunnel-technikaval-es-palat-01.jpg", "alt": "Többszörös ínyrecesszió kezelése tunnel technikával és palatinális kötőszövetes szabadlebennyel – 1. kép (előtte)", "width": 3888, "height": 2592, "label": "előtte"},
      {"src": "/esetek/tobbszoros-inyrecesszio-kezelese-tunnel-technikaval-es-palat-02.jpg", "alt": "Többszörös ínyrecesszió kezelése tunnel technikával és palatinális kötőszövetes szabadlebennyel – 2. kép (utána)", "width": 3888, "height": 2592, "label": "utána"},
      {"src": "/esetek/tobbszoros-inyrecesszio-kezelese-tunnel-technikaval-es-palat-03.jpg", "alt": "Többszörös ínyrecesszió kezelése tunnel technikával és palatinális kötőszövetes szabadlebennyel – 3. kép", "width": 3888, "height": 2592},
      {"src": "/esetek/tobbszoros-inyrecesszio-kezelese-tunnel-technikaval-es-palat-04.jpg", "alt": "Többszörös ínyrecesszió kezelése tunnel technikával és palatinális kötőszövetes szabadlebennyel – 4. kép", "width": 3888, "height": 2592},
      {"src": "/esetek/tobbszoros-inyrecesszio-kezelese-tunnel-technikaval-es-palat-05.jpg", "alt": "Többszörös ínyrecesszió kezelése tunnel technikával és palatinális kötőszövetes szabadlebennyel – 5. kép", "width": 3888, "height": 2592},
      {"src": "/esetek/tobbszoros-inyrecesszio-kezelese-tunnel-technikaval-es-palat-06.jpg", "alt": "Többszörös ínyrecesszió kezelése tunnel technikával és palatinális kötőszövetes szabadlebennyel – 6. kép", "width": 1024, "height": 682},
      {"src": "/esetek/tobbszoros-inyrecesszio-kezelese-tunnel-technikaval-es-palat-07.jpg", "alt": "Többszörös ínyrecesszió kezelése tunnel technikával és palatinális kötőszövetes szabadlebennyel – 7. kép", "width": 3888, "height": 2592},
      {"src": "/esetek/tobbszoros-inyrecesszio-kezelese-tunnel-technikaval-es-palat-08.jpg", "alt": "Többszörös ínyrecesszió kezelése tunnel technikával és palatinális kötőszövetes szabadlebennyel – 8. kép", "width": 3888, "height": 2592},
      {"src": "/esetek/tobbszoros-inyrecesszio-kezelese-tunnel-technikaval-es-palat-09.jpg", "alt": "Többszörös ínyrecesszió kezelése tunnel technikával és palatinális kötőszövetes szabadlebennyel – 9. kép", "width": 3888, "height": 2592},
      {"src": "/esetek/tobbszoros-inyrecesszio-kezelese-tunnel-technikaval-es-palat-10.jpg", "alt": "Többszörös ínyrecesszió kezelése tunnel technikával és palatinális kötőszövetes szabadlebennyel – 10. kép", "width": 3888, "height": 2592},
      {"src": "/esetek/tobbszoros-inyrecesszio-kezelese-tunnel-technikaval-es-palat-11.jpg", "alt": "Többszörös ínyrecesszió kezelése tunnel technikával és palatinális kötőszövetes szabadlebennyel – 11. kép", "width": 3888, "height": 2592},
      {"src": "/esetek/tobbszoros-inyrecesszio-kezelese-tunnel-technikaval-es-palat-12.jpg", "alt": "Többszörös ínyrecesszió kezelése tunnel technikával és palatinális kötőszövetes szabadlebennyel – 12. kép", "width": 3888, "height": 2592},
      {"src": "/esetek/tobbszoros-inyrecesszio-kezelese-tunnel-technikaval-es-palat-13.jpg", "alt": "Többszörös ínyrecesszió kezelése tunnel technikával és palatinális kötőszövetes szabadlebennyel – 13. kép", "width": 3888, "height": 2592},
      {"src": "/esetek/tobbszoros-inyrecesszio-kezelese-tunnel-technikaval-es-palat-14.jpg", "alt": "Többszörös ínyrecesszió kezelése tunnel technikával és palatinális kötőszövetes szabadlebennyel – 14. kép", "width": 1024, "height": 682},
    ],
  },
  {
    "slug": "alveolus-prezervacio-elotte-utana",
    "title": "Alveólus prezerváció előtte – utána",
    "description": "",
    "images": [
      {"src": "/esetek/alveolus-prezervacio-elotte-utana-01.jpg", "alt": "Alveólus prezerváció előtte – utána – 1. kép", "width": 2048, "height": 1536},
      {"src": "/esetek/alveolus-prezervacio-elotte-utana-02.jpg", "alt": "Alveólus prezerváció előtte – utána – 2. kép", "width": 640, "height": 480},
      {"src": "/esetek/alveolus-prezervacio-elotte-utana-03.jpg", "alt": "Alveólus prezerváció előtte – utána – 3. kép", "width": 640, "height": 480},
      {"src": "/esetek/alveolus-prezervacio-elotte-utana-04.jpg", "alt": "Alveólus prezerváció előtte – utána – 4. kép", "width": 2048, "height": 1536},
      {"src": "/esetek/alveolus-prezervacio-elotte-utana-05.jpg", "alt": "Alveólus prezerváció előtte – utána – 5. kép", "width": 2048, "height": 1536},
      {"src": "/esetek/alveolus-prezervacio-elotte-utana-06.jpg", "alt": "Alveólus prezerváció előtte – utána – 6. kép", "width": 1024, "height": 758},
    ],
  },
  {
    "slug": "agressziv-fogagybetegseg-soran-elvandorolt-nagymetszofog",
    "title": "Agresszív fogágybetegség során elvándorolt nagymetszőfog",
    "description": "…és ami közte történt, közel 1,5 év alatt:",
    "images": [
      {"src": "/esetek/agressziv-fogagybetegseg-soran-elvandorolt-nagymetszofog-01.jpg", "alt": "Agresszív fogágybetegség során elvándorolt nagymetszőfog – 1. kép (előtte)", "width": 3888, "height": 2592, "label": "előtte"},
      {"src": "/esetek/agressziv-fogagybetegseg-soran-elvandorolt-nagymetszofog-02.jpg", "alt": "Agresszív fogágybetegség során elvándorolt nagymetszőfog – 2. kép (utána)", "width": 3888, "height": 2592, "label": "utána"},
      {"src": "/esetek/agressziv-fogagybetegseg-soran-elvandorolt-nagymetszofog-03.jpg", "alt": "Agresszív fogágybetegség során elvándorolt nagymetszőfog – 3. kép", "width": 3888, "height": 2592},
      {"src": "/esetek/agressziv-fogagybetegseg-soran-elvandorolt-nagymetszofog-04.jpg", "alt": "Agresszív fogágybetegség során elvándorolt nagymetszőfog – 4. kép", "width": 3888, "height": 2592},
      {"src": "/esetek/agressziv-fogagybetegseg-soran-elvandorolt-nagymetszofog-05.jpg", "alt": "Agresszív fogágybetegség során elvándorolt nagymetszőfog – 5. kép", "width": 3888, "height": 2592},
      {"src": "/esetek/agressziv-fogagybetegseg-soran-elvandorolt-nagymetszofog-06.jpg", "alt": "Agresszív fogágybetegség során elvándorolt nagymetszőfog – 6. kép", "width": 3888, "height": 2592},
      {"src": "/esetek/agressziv-fogagybetegseg-soran-elvandorolt-nagymetszofog-07.jpg", "alt": "Agresszív fogágybetegség során elvándorolt nagymetszőfog – 7. kép", "width": 3888, "height": 2592},
      {"src": "/esetek/agressziv-fogagybetegseg-soran-elvandorolt-nagymetszofog-08.jpg", "alt": "Agresszív fogágybetegség során elvándorolt nagymetszőfog – 8. kép", "width": 3888, "height": 2592},
      {"src": "/esetek/agressziv-fogagybetegseg-soran-elvandorolt-nagymetszofog-09.jpg", "alt": "Agresszív fogágybetegség során elvándorolt nagymetszőfog – 9. kép", "width": 3888, "height": 2592},
      {"src": "/esetek/agressziv-fogagybetegseg-soran-elvandorolt-nagymetszofog-10.jpg", "alt": "Agresszív fogágybetegség során elvándorolt nagymetszőfog – 10. kép", "width": 3888, "height": 2592},
    ],
  },
  {
    "slug": "teljes-fogatlansag-kezelese-implantatummal",
    "title": "Teljes fogatlanság kezelése implantátummal",
    "description": "",
    "images": [
      {"src": "/esetek/teljes-fogatlansag-kezelese-implantatummal-01.jpg", "alt": "Teljes fogatlanság kezelése implantátummal – 1. kép", "width": 3888, "height": 2592},
      {"src": "/esetek/teljes-fogatlansag-kezelese-implantatummal-02.jpg", "alt": "Teljes fogatlanság kezelése implantátummal – 2. kép", "width": 3888, "height": 2592},
    ],
  },
  {
    "slug": "cirkon-korona-elotte-utana",
    "title": "Cirkón korona előtte – utána",
    "description": "",
    "images": [
      {"src": "/esetek/cirkon-korona-elotte-utana-01.jpg", "alt": "Cirkón korona előtte – utána – 1. kép", "width": 3888, "height": 2592},
      {"src": "/esetek/cirkon-korona-elotte-utana-02.jpg", "alt": "Cirkón korona előtte – utána – 2. kép", "width": 3888, "height": 2592},
    ],
  },
  {
    "slug": "ketoldali-sorvegi-foghiany-potlasa-implantatumokkal-az-also",
    "title": "Kétoldali sorvégi foghiány pótlása implantátumokkal az alsó állcsonton",
    "description": "",
    "images": [
      {"src": "/esetek/ketoldali-sorvegi-foghiany-potlasa-implantatumokkal-az-also-01.jpg", "alt": "Kétoldali sorvégi foghiány pótlása implantátumokkal az alsó állcsonton – 1. kép", "width": 846, "height": 459},
      {"src": "/esetek/ketoldali-sorvegi-foghiany-potlasa-implantatumokkal-az-also-02.jpg", "alt": "Kétoldali sorvégi foghiány pótlása implantátumokkal az alsó állcsonton – 2. kép", "width": 846, "height": 459},
      {"src": "/esetek/ketoldali-sorvegi-foghiany-potlasa-implantatumokkal-az-also-03.jpg", "alt": "Kétoldali sorvégi foghiány pótlása implantátumokkal az alsó állcsonton – 3. kép", "width": 3888, "height": 2592},
      {"src": "/esetek/ketoldali-sorvegi-foghiany-potlasa-implantatumokkal-az-also-04.jpg", "alt": "Kétoldali sorvégi foghiány pótlása implantátumokkal az alsó állcsonton – 4. kép", "width": 3888, "height": 2592},
      {"src": "/esetek/ketoldali-sorvegi-foghiany-potlasa-implantatumokkal-az-also-05.jpg", "alt": "Kétoldali sorvégi foghiány pótlása implantátumokkal az alsó állcsonton – 5. kép", "width": 3888, "height": 2592},
      {"src": "/esetek/ketoldali-sorvegi-foghiany-potlasa-implantatumokkal-az-also-06.jpg", "alt": "Kétoldali sorvégi foghiány pótlása implantátumokkal az alsó állcsonton – 6. kép", "width": 3888, "height": 2592},
    ],
  },
];
